name: Infrastructure Continuous Deployment

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: "1.6.1"

        - name: terraform-plan #Generates a terraform plan and attaches it to a PR if triggering event is a PR. 
          uses: dflook/terraform-plan@v1.41.1
          with:
            tf_actions_working_dir: terraform/
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Apply Terraform Changes
          uses: hashicorp/terraform-github-actions/apply@v0.4.0
          with:
            tf_actions_working_dir: terraform/
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}