# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linting + Testing

on:
  push:
    branches:
      - 'main'
      - 'develop'
      
  pull_request:
    branches:
      - 'main'
      - 'develop'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff ./app ./src/lambda/recent_observations_lambda.py --line-length=100
    - name: Test with pytest
      env:
        EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}
      run: |
        pytest
